-- Users table for storing user profiles
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Rooms table for storing scanned room data
CREATE TABLE rooms (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    room_type VARCHAR(100), -- living_room, bedroom, kitchen, etc.
    dimensions JSONB, -- room dimensions and layout data from ARKit
    scan_data JSONB, -- ARKit mesh and anchor data
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Furniture categories
CREATE TABLE furniture_categories (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Furniture items (from Amazon or other sources)
CREATE TABLE furniture_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    category_id UUID REFERENCES furniture_categories(id),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    amazon_asin VARCHAR(20),
    image_url VARCHAR(500),
    dimensions JSONB, -- width, height, depth
    style_tags TEXT[], -- modern, rustic, minimalist, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User saved designs
CREATE TABLE saved_designs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    furniture_layout JSONB, -- positions and rotations of furniture
    style_preferences JSONB, -- user's style choices
    budget_range JSONB, -- min/max budget
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Furniture recommendations generated by AI
CREATE TABLE furniture_recommendations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
    furniture_item_id UUID REFERENCES furniture_items(id),
    position JSONB, -- 3D position in room
    rotation JSONB, -- 3D rotation
    confidence_score DECIMAL(3,2), -- AI confidence (0.00-1.00)
    reasoning TEXT, -- AI explanation for recommendation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for better performance
CREATE INDEX idx_rooms_user_id ON rooms(user_id);
CREATE INDEX idx_saved_designs_user_id ON saved_designs(user_id);
CREATE INDEX idx_saved_designs_room_id ON saved_designs(room_id);
CREATE INDEX idx_furniture_recommendations_room_id ON furniture_recommendations(room_id);
CREATE INDEX idx_furniture_items_category_id ON furniture_items(category_id);
CREATE INDEX idx_furniture_items_style_tags ON furniture_items USING GIN(style_tags);